### ISSUE TITLE
Unable to add screenshots to the report

### ISSUE THREAD

**Issue by hari49951** [webnexusmobile/cypress-cucumber-getting-started#3]
@webnexusmobile Thanks for the solution to generate the reports. I am able to generate reports using your code. If there are any failures in any scenarios and when I run node ./cypress/reporting/report.js to generate reports with screenshots getting below error. 

    Adding screenshot to cucumber-json report for
    'Testing for new functions sanity'
C:\Users\{project}\cypress\reporting\report.js:74
      const myScenarios = cucumberReportMap[feature][0].elements.filter(
                                                    ^

TypeError: Cannot read property '0' of undefined
    at C:\Users\{project}\cypress\reporting\report.js:74:53
    at Array.forEach (<anonymous>)
    at C:\Users\{project}\cypress\reporting\report.js:63:17
    at Array.forEach (<anonymous>)
    at addScreenshots (C:\Users\{project}\cypress\reporting\report.js:62:16)
    at Object.<anonymous> (C:\Users\{project}\cypress\reporting\report.js:24:1)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! report: `node ./cypress/reporting/report.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the report script.

**Comment by zettpunkt79** [comment]
Without knowing your project structure I can only guess. Please verify that your screenshots live in a folder that matches your feature file, like:
```shell
./integration/example.feature
./screenshots/example.feature/Example -- Testing for new functions sanity (failed).png
```
or
```shell
./integration/subfolder/example.feature
./screenshots/subfolder/example.feature/Example -- Testing for new functions sanity (failed).png
```

Are you maybe using any special characters in your feature-file's filename?

**Comment by vio-codes** [comment]
@webnexusmobile that structure is generated only if you use the naming pattern provided by cypress, if you have the nonGlobalStepDefinition to false, do they generate the same structure?

**Comment by zettpunkt79** [comment]
The whole report mechanism in this repo is build for the project setup as provided in this repo so I cannot guarantee
 that the reporting works for different project setups without adapting the report.js. Nevertheless I tried setting the nonGlobalStepDefinition to false and the screenshot for a failing scenario was added as expected.
