### ISSUE TITLE
is it a way to add on demand screenshots to a report?

### ISSUE THREAD

**Issue by jradom** [webnexusmobile/cypress-cucumber-getting-started#4]
Hello,

I was able to successfully generate a failed screenshot.  But if for example I need to add a screenshot on a certain step can you suggest how can I do that?  Also, I'm interested to add some text to a report or attach a file.

Please, help

Thanks

Jeff

**Comment by zettpunkt79** [comment]
Hello,

this repo's only purpose is to provide a quick start if one wants to add screenshots to the exact same steps which created a screenshot, be it because of a failure or on purpose. So your request ist a little out of scope for this demo. But since the cucumber report files are in JSON format you can add any additional info to the JSON files before generating the HTML report. The report.js located in the cypress/reporting folder should provide you with all the details on how to add a file to the JSON structure of the cucumber report files.

**Comment by jradom** [comment]
I’m very new to Cypress and JavaScript. So, can you please give me a bit of guidance what/how should I expand your code?  I’m also curious if I can attach a text file for example at one of a step  Any help will be greatly appreciated

Thanks 

Jeff

**Comment by zettpunkt79** [comment]
Adding on demand screenshots works out of the box in my example, take a look at the scenario "I can take a screenshot which is integrated in the report" within the feature file. It's a quick and dirty solution but it does the trick for now.
Adding a text file is a whole other story. You would have to find a way to determine the current feature and scenario name and use this to generate a filename which would have to look something like this: `${featureName} -- ${scenarioName}.txt` and write the file via `cy.writeFile()`. From there on there wouldn't be much more to do than to modify the `report.js` so it can handle *.txt files in a similar manner as it currently handles the *.png screenshots and snapshots.

You might want to check out https://github.com/Shelex/cypress-allure-plugin. Sounds like this library supports all you are looking for by default.

**Comment by jradom** [comment]
I've just tried your suggestion adding non-failed screenshot using your
reporter code and got a runtime error message.  Do i miss something?.
Please, advise
[image: image.png]

Thanks

Jeff

**Comment by zettpunkt79** [comment]
I would need more details to tell. Cannot see the image you tried to attach.

**Comment by jradom** [comment]
here you are ...
[image: image.png]

**Comment by jradom** [comment]
and this is the code I've used.  I've added some experiments related to
videos but all is commented out for now

const report = require('multiple-cucumber-html-reporter')
const fs = require('fs-extra')
const path = require('path')
const chalk = require('chalk')

const cucumberJsonDir = './cucumber-json'
const cucumberReportFileMap = {}
const cucumberReportMap = {}
const videosMap = {};
const jsonIndentLevel = 2
const htmlReportDir = './test-results/html'
const screenshotsDir = './screenshots'
const videosDir = "./videos";
const videosPath = videosDir; ///path.join(__dirname, "..", videosDir);

const videos = fs.readdirSync(videosPath);
videos.forEach(vid => {
    const arr = vid.split(".");
    const featureName = `${arr[0]}.${arr[1]}`;
    videosMap[featureName] = vid;
});

getCucumberReportMaps();
addScreenshots();
generateReport();

function getCucumberReportMaps() {
    const files = fs.readdirSync(cucumberJsonDir).filter(file => {
        return file.indexOf('.json') > -1
    })
    files.forEach(file => {
        const json = JSON.parse(
            fs.readFileSync(path.join(cucumberJsonDir, file))
        )
        if (!json[0]) { return }
        const [feature] = json[0].uri.split('/').reverse()
        cucumberReportFileMap[feature] = file
        cucumberReportMap[feature] = json
    })
}

function addScreenshots() {
    const prependPathSegment = pathSegment => location =>
path.join(pathSegment, location)
    // fs.readdir but with relative paths
    const readdirPreserveRelativePath = location =>
fs.readdirSync(location).map(prependPathSegment(location))
    // Recursive fs.readdir but with relative paths
    const readdirRecursive = location => readdirPreserveRelativePath(location)
        .reduce((result, currentValue) =>
fs.statSync(currentValue).isDirectory()
            ? result.concat(readdirRecursive(currentValue))
            : result.concat(currentValue), [])
    const screenshots =
readdirRecursive(path.resolve(screenshotsDir)).filter(file => {
        return file.indexOf('.png') > -1
    })
    // Extract feature list from screenshot list
    const featuresList = Array.from(new Set(screenshots.map(x =>
x.match(/[\w-_.]+\.feature/g)[0])))
    featuresList.forEach(feature => {
        screenshots.forEach(screenshot => {
            const regex = /(?<=--\ ).+?((?=\ \(example\ #\d+\))|(?=\
\(failed\))|(?=\.\w{3}))/g
            const [scenarioName] = screenshot.match(regex)
            console.info(chalk.blue('\n    Adding screenshot to
cucumber-json report for'))
            console.info(chalk.blue(`    '${scenarioName}'`))
            // Find all scenarios matching the scenario name of the screenshot.
            // This is important when using the scenario outline mechanism
            const myScenarios = cucumberReportMap[feature][0].elements.filter(
                e => scenarioName.includes(e.name)
            )
            if (!myScenarios) { return }
            let foundFailedStep = false
            myScenarios.forEach(myScenario => {
                if (foundFailedStep) {
                    return
                }
                let myStep
                if (screenshot.includes('(failed)')) {
                    myStep = myScenario.steps.find(
                        step => step.result.status === 'failed'
                    )
                } else {
                    myStep = myScenario.steps.find(
                        step => step.name.includes('screenshot')
                    )
                }
                if (!myStep) {
                    return
                }
                const data = fs.readFileSync(
                    path.resolve(screenshot)
                )
                if (data) {
                    const base64Image = Buffer.from(data,
'binary').toString('base64')
                    if (!myStep.embeddings) {
                        myStep.embeddings = []
                        myStep.embeddings.push({ data: base64Image,
mime_type: 'image/png' })
                        foundFailedStep = true
                    }
                }

                /// add video
/*

                const vidData = fs
                    .readFileSync(path.join(videosPath, videosMap[feature]))
                    .toString("base64");
                if (vidData) {
                    const html = `<video controls width="500"><source
type="video/mp4" src="data:video/mp4;base64,${vidData}"> </video>`;
                    const encodedHtml = Buffer.from(html,
"binary").toString("base64");
                    myStep.embeddings.push({ data: encodedHtml,
mime_type: "text/html" });
                }
*/
        //===========================================================================



            })
            //Write JSON with screenshot back to report file.
            fs.writeFileSync(
                path.join(cucumberJsonDir, cucumberReportFileMap[feature]),
                JSON.stringify(cucumberReportMap[feature], null,
jsonIndentLevel)
            )
        })
    })
}

function generateReport() {
    if (!fs.existsSync(cucumberJsonDir)) {
        console.warn(chalk.yellow(`WARNING: Folder
'./${cucumberJsonDir}' not found. REPORT CANNOT BE CREATED!`))
    } else {
        report.generate({
            jsonDir: cucumberJsonDir,
            reportPath: htmlReportDir,
            displayDuration: true,
            displayReportTime: true,
            pageTitle: 'System-Test Report',
            reportName: `System-Test Report - ${new Date().toLocaleString()}`,
            hideMetadata: true
        })
    }
}

**Comment by jradom** [comment]
and my JSON file is

[
  {
    "description": "  As a valid customer I'm able to login into CAIR
site\n  and start creating a case",
    "keyword": "Feature",
    "name": "Login Feature",
    "line": 1,
    "id": "login-feature",
    "tags": [],
    "uri": "justLogin.feature",
    "elements": [
      {
        "id": "login-feature;login-validation",
        "keyword": "Scenario",
        "line": 6,
        "name": "Login Validation",
        "tags": [
          {
            "name": "@mytag3",
            "line": 5
          }
        ],
        "type": "scenario",
        "steps": [
          {
            "arguments": [],
            "keyword": "Given ",
            "line": 7,
            "name": "I am finally on CAIR login page",
            "result": {
              "status": "passed",
              "duration": 8321000000
            }
          }
        ]
      }
    ]
  }
]

**Comment by jradom** [comment]
![Uploading image.png…]()

**Comment by jradom** [comment]
![image](https://user-images.githubusercontent.com/20550461/102025010-12f74000-3d4a-11eb-94e6-cec55b2b01b9.png)

**Comment by zettpunkt79** [comment]
Cannot look into this in detail right now but I noticed two things: My feature files live directly inside the integration folder. Your are using an additional folder level and I don't think the reporter takes this into account in it's current state. Furthermore, to identify the step which the screenshot should be attached to, the reporter currently looks for the substring "screenshot" within the step name. As mentioned, this is quick and dirty and any better ideas are very welcome.

**Comment by jradom** [comment]
I'll try later the same folder structure works great with failed screenshots

**Comment by jradom** [comment]
this is screenshot with "good" run
![image](https://user-images.githubusercontent.com/20550461/102025809-3bce0400-3d4f-11eb-83a0-f7d070a7db12.png)

**Comment by jradom** [comment]
I did use your suggestions but unfortunately they didn't help and I see the
same error

[image: image.png]

**Comment by jradom** [comment]
I think my problem in comparison what you got is a folder structure and names.  But Ion't know how I can adijust your.  I've did some debugging thought,

![image](https://user-images.githubusercontent.com/20550461/102062132-2f769500-3da9-11eb-8339-c5daef11cb30.png)

**Comment by jradom** [comment]
You have an above parameter true which makes my stuff very different.  Please, help if you can

Thanks

Jeff

**Comment by jradom** [comment]
FYI, here is similar to mine issue discussed https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/251

**Comment by zettpunkt79** [comment]
I tried a similar folder structure as yours combined with `"nonGlobalStepDefinitions": false` and still had no problems.
But I noticed something in your screenshots. Your filename "my_login.png" differs of what cypress would save by default which would be something like `${featureName} -- ${scenarioName}.png`. The report.js expects this naming scheme to find the right spot to append the screenshot within the *.json.

**Comment by jradom** [comment]
It might be a reason.  Please, send me a real example how your
screenshot file name looks like?  Meanwhile I'll try manually adding a
prefix to the file name in cy.screenshot().  BTW, do you use the above
command or something else?

Thanks

Jeff

**Comment by jradom** [comment]
I've added in the code a prefix containing feature name.  So, I didn't error any longer but a screenshot wasn't added to a JSON file.  Any suggestions?
![image](https://user-images.githubusercontent.com/20550461/102113751-3ecc0180-3dee-11eb-8aa4-1e336eedd45d.png)

**Comment by jradom** [comment]
I think adding a prefix did some good but it might it wasn't enough because when I added a lo for Regex retun it still shows old file name if I'm not mistaken
my JSON file is
[
  {
    "description": "  As a valid customer I'm able to login into CAIR site\n  and start creating a case",
    "keyword": "Feature",
    "name": "Login Feature",
    "line": 1,
    "id": "login-feature",
    "tags": [],
    "uri": "justLogin.feature",
    "elements": [
      {
        "id": "login-feature;login-validation",
        "keyword": "Scenario",
        "line": 6,
        "name": "Login Validation",
        "tags": [
          {
            "name": "@mytag3",
            "line": 5
          }
        ],
        "type": "scenario",
        "steps": [
          {
            "arguments": [],
            "keyword": "Given ",
            "line": 7,
            "name": "I am finally on CAIR login page",
            "result": {
              "status": "passed",
              "duration": 7327000000
            }
          },
          {
            "arguments": [],
            "keyword": "And ",
            "line": 8,
            "name": "I make my own screenshot",
            "result": {
              "status": "passed",
              "duration": 1231000000
            }
          }
        ]
      }
    ]
  }
]

**Comment by jradom** [comment]
Oh, I think i missed a scenarion name in screenshot name.  making change and rerunning

**Comment by zettpunkt79** [comment]
Just use `cy.screenshot()` without any parameters and see for yourself.

**Comment by jradom** [comment]
Great, it did work very well now.  But is it a way somehow to improve your code a bit that I wont't need to add prefix to file name manually ?  I mean if you'll a bit of time for that

**Comment by zettpunkt79** [comment]
As mentioned above, just use `cy.screenshot()`without parameters. It will save a screenshot with the expected filename.

**Comment by jradom** [comment]
I'll try, thanks

**Comment by jradom** [comment]
Great,  Id did work very well.  Now if for example I have several scenarios (passed and failed), will that work?  Please, let me know.

Oh, is it easy to add also text attachments?  I recall a conversation you or somebody else mentioned was working a while ago 

Thanks

jeff

**Comment by jradom** [comment]
PDF attaching is really as addition for now I'm looking for pretty urgently.  It's because current Protractor reports allow to do it easily.  We actually porting Typescript/Protractor tests to Cypress/Cucumber/Typescript
