### ISSUE TITLE
Is it a way to add PDF, CSV, TXT files or just a note to a report?

### ISSUE THREAD

**Issue by jradom** [webnexusmobile/cypress-cucumber-getting-started#5]
Is it a way to add PDF, CSV, TXT files or just a note to a report to a particular step?  And if it is, what would be suggested in order to do that?

**Comment by zettpunkt79** [comment]
This is out of scope of this demo project. To make this work you would have to build a post-processor which leverages the cucumber-report files with binaries. The algorithm would be quite similar to the one which is currently adding the *.png files to the JSON-structure of the cucumber report file.
